---

- fail: msg="Please specify tarsnap key"
  when: "{{ TARSNAP_KEY == None }}"

- fail: msg="Please configure TARSNAP_BACKUP_FOLDERS, we want all servers to be backed up :)"
  when: "{{ TARSNAP_BACKUP_FOLDERS == None }}"

# Note: tarsnap.key template is actually neccessaty. YAML strips whitespace from
# variables, and tarsnap requires key to end with a newline.
- name: Copy key file into place
  template:
    src: tarsnap.key
    dest: "{{ TARSNAP_KEY_REMOTE_LOCATION }}"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Create cache directory
  file: state=directory path={{ TARSNAP_CACHE }} owner=root group=root mode=750

- name: template main backup script
  template:
    src: "backup.sh"
    dest: "{{ TARSNAP_BACKUP_SCRIPT_LOCATION }}"
    owner: root
    group: root
    mode: "500"

- name: Check we can access tarsnap and run fsck
  command: tarsnap --cachedir {{ TARSNAP_CACHE }} --keyfile {{ TARSNAP_KEY_REMOTE_LOCATION }} --fsck

- name: Install backup in cron
  cron:
    name: "Backup for this server, archive: {{ TARSNAP_ARCHIVE_NAME }}"
    job: "{{ TARSNAP_BACKUP_SCRIPT_LOCATION }} > /dev/null 2>&1"
    hour: "{{ TARSNAP_BACKUP_HOUR }}"
    minute: "{{ TARSNAP_BACKUP_MINUTE }}"
    state: "{{ TARSNAP_CRONTAB_STATE }}"