---
# Tarsnap - backup

- name: Copy key file into place
  template:
    src: "{{ TARSNAP_KEY_LOCAL_TEMPLATE }}"
    dest: "{{ TARSNAP_KEY_REMOTE_LOCATION }}"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Create cache directory
  file: state=directory path={{ TARSNAP_CACHE }} owner=root group=root mode=750

- name: Copy pre-backup script, if any
  copy:
    src: "{{ TARSNAP_PRE_BACKUP_SCRIPT }}"
    dest: "{{ TARSNAP_PRE_BACKUP_SCRIPT_REMOTE_LOCATION }}"
    owner: root
    group: root
    mode: "755"
  when: "{{ TARSNAP_PRE_BACKUP_SCRIPT }}"

- name: Check we can access tarsnap and run fsck
  command: tarsnap --cachedir {{ TARSNAP_CACHE }} --keyfile {{ TARSNAP_KEY_REMOTE_LOCATION }} --fsck
