---
# Tarsnap - backup

- fail: msg="Please configure tarsnap role, we want all servers to be backed up :)"
  when: "{{ TARSNAP_KEY == None or TARSNAP_BACKUP_FOLDERS == None }}"

- name: Copy key file into place
  copy:
    content: "{{ TARSNAP_KEY }}"
    dest: "{{ TARSNAP_KEY_REMOTE_LOCATION }}"
    owner: "root"
    group: "root"
    mode: "0600"

- name: Create cache directory
  file: state=directory path={{ TARSNAP_CACHE }} owner=root group=root mode=750

- name: Copy pre-backup script, if any
  copy:
    src: "{{ TARSNAP_PRE_BACKUP_SCRIPT }}"
    dest: "{{ TARSNAP_PRE_BACKUP_SCRIPT_REMOTE_LOCATION }}"
    owner: root
    group: root
    mode: "500"
  when: "{{ TARSNAP_PRE_BACKUP_SCRIPT }}"

- name: Copy post-backup script, if any
  copy:
    src: "{{ TARSNAP_POST_BACKUP_SCRIPT }}"
    dest: "{{ TARSNAP_POST_BACKUP_SCRIPT_REMOTE_LOCATION }}"
    owner: root
    group: root
    mode: "500"
  when: "{{ TARSNAP_POST_BACKUP_SCRIPT }}"

- name: template main backup script
  template:
    src: "backup.sh"
    dest: "{{ TARSNAP_BACKUP_SCRIPT_LOCATION }}"
    owner: root
    group: root
    mode: "500"

- name: Check we can access tarsnap and run fsck
  command: tarsnap --cachedir {{ TARSNAP_CACHE }} --keyfile {{ TARSNAP_KEY_REMOTE_LOCATION }} --fsck

- name: Install backup in cron
  cron:
    job: "{{ TARSNAP_BACKUP_SCRIPT_LOCATION }} > /dev/null 2> &1"
    hour: "{{ TARSNAP_BACKUP_HOUR }}"
    minute: "{{ TARSNAP_BACKUP_MINUTE }}"